dist: trusty
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist --ignore-platform-reqs

script:
  - vendor/bin/phpunit
